### PR TITLE
handle exceptions in middleware

### PR DESCRIPTION
**Pull request by SergeyFilenko**
The problem is this request returns an empty response

https://ws3.morpher.ru/get_queries_left_for_today?token=invalid_token

whereas it should return an error XML/JSON similar to this:

https://ws3.morpher.ru/russian/declension?s=%D0%9F%D0%BE%D0%BB%D1%8C%D0%B7%D0%BE%D0%B2%D0%B0%D1%82%D0%B5%D0%BB%D1%8C&token=invalid_token

### CODE REVIEW

**Comment by bzaar** [comment]
Why modify an existing class when you can add a new class? See also the Single Responsibility Principle.

**Comment by SergeyFilenko** [comment]
Done

**Comment by bzaar** [comment]
I don't understand why so many changes. The goal was to send an email when an exception occurs, is that correct? 

That goal can be achieved by simply adding a new middleware class at the top of the middleware stack that calls all the other middleware classes, catches any exception, logs them, and rethrows.

Or was there something else that we wanted to do here?

**Comment by bzaar** [comment]
By the way, we don't need any XML or JSON returned on the case of HTTP 500. Returning a more extended error message can be a security threat as it can expose database names, file locations, etc.

**Comment by SergeyFilenko** [comment]
I've just added new middleware class, removed exception handling in throttling middleware because you don't want handle it manually when you have special middleware, added exception middleware to the tests

**Comment by SergeyFilenko** [comment]
> By the way, we don't need any XML or JSON returned on the case of HTTP 500. Returning a more extended error message can be a security threat as it can expose database names, file locations, etc.

We are not returning extended error message, we are returning this in case of 500 - https://github.com/morpher-ru/Morpher.WebService.V3/blob/master/Morpher.WebApi/General/Data/Exceptions/ServerException.cs

**Comment by bzaar** [comment]
Can we just leave all middleware classes as before and just add this class:

    public class ExceptionHandlingMiddleware : OwinMiddleware
    {
        public override async Task Invoke(IOwinContext context)
        {
            try
            {
                await Next.Invoke(context);
            }
            catch (Exception exc)
            {
                Mail.SendErrorEmail(exc);
                throw;
            }
        }
    }
 
Will this work?

**Comment by SergeyFilenko** [comment]
No, user will receive an empty 200 response. ExceptionFilter can't catch exception occured inside OWIN Middleware

**Comment by bzaar** [comment]
OK can we remove `MorpherExceptionFilterAttribute` then? It has the same code as `ExceptionHandlingMiddleware` (copied and pasted, I suspect) ;)

**Comment by SergeyFilenko** [comment]
Ehhh no. Not really copypasted. In asp.net web api owin middleware can't catch exception raised in Controller (it's possible in asp.net mvc5 && .net core asp.net) And you can see the difference. They are writing to a different context, so it's look same, doing same, but using another methods.

**Comment by bzaar** [comment]
Looks like we've chosen the wrong technology.

OK how about this?

Can we just leave all middleware classes as before and just add this class (spot one difference!):

    public class ExceptionHandlingMiddleware : OwinMiddleware
    {
        public override async Task Invoke(IOwinContext context)
        {
            try
            {
                await Next.Invoke(context);
            }
            catch (Exception exc)
            {
                Mail.SendErrorEmail(exc);
                context.Response.StatusCode = 500;
                throw;
            }
        }
    }
 
Will this work?

**Comment by bzaar** [comment]
How about a unit test to verify that the issue has been resolved?

**Comment by SergeyFilenko** [comment]
I've added two tests, one is testing an exception raised inside middleware, and another one an exception raised inside a controller.

**Pull request closed without merging**
